spring.application.name=demo
# MySQL DB 연결 설정
spring.profiles.include=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


# JPA / Hibernate 설정
# update: 서버가 켜질 때 Entity 클래스(User)를 보고 자동으로 DB 테이블을 생성/수정해줍니다.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect